must_have_words = ["Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh", "Phan", "Vũ", "Võ", "Đặng", "Bùi", "Đỗ", "Hồ",
                       "Ngô", "Dương", "Lý", "An", "Anh", "Ao", "Ánh", "Ân", "Âu", "Bá", "Bạc", "Bạch", "Bàn", "Bàng",
                       "Bành", "Bảo", "Bế", "Bì", "Biện", "Bình", "Bồ", "Chriêng", "Ca", "Cái", "Cam", "Canh", "Cao",
                       "Cáp", "Cát", "Cầm", "Cấn", "Chế", "Chiêm", "Chu", "Châu", "Chung", "Chúng", "Chương", "Chử",
                       "Cồ", "Cổ", "Công", "Cống", "Cung", "Cù", "Cự", "Dã", "Danh", "Diêm", "Diệp", "Doãn", "Dư",
                       "Đái", "Điều", "Đan", "Đàm", "Đào", "Đậu", "Đèo", "Điền", "Đinh", "Điêu", "Đoàn", "Đôn", "Đống",
                       "Đồ", "Đồng", "Đổng", "Đới", "Đương", "Đường", "Đức", "Đăng", "Giả", "Giao", "Giang", "Giàng",
                       "Giáp", "H'", "H'ma", "H'nia", "Hầu", "Hà", "Hạ", "Hàn", "Hán", "Hề", "Hi", "Hình", "Hoa",
                       "Hồng", "Hoàng", "Hùng", "Hứa", "Hướng", "Kông", "Kiểu", "Kiều", "Kha", "Khương", "Khâu", "Khấu",
                       "Khiếu", "Khoa", "Khổng", "Khu", "Khuất", "Khúc", "Kim", "Lyly", "La", "Lã", "Lãnh", "Lạc",
                       "Lại", "Lăng", "Lâm", "Lèng", "Lều", "Liêu", "Liễu", "Lò", "Lỗ", "Lộ", "Luyện", "Lục", "Lư",
                       "Lương", "Lưu", "Lý", "Mùa", "Ma", "Mai", "Mang", "Mã", "Mạch", "Mạnh", "Mâu", "Mẫn", "Mộc",
                       "Mục", "Nhan", "Ninh", "Nhâm", "Ngân", "Nghiêm", "Nghị", "Ngọ", "Ngọc", "Ngụy", "Nhữ", "Nông",
                       "Ong", "Ông", "Phi", "Phí", "Phó", "Phú", "Phùng", "Phương", "Quản", "Quàng", "Quách", "Sầm",
                       "Sơn", "Sử", "Sùng", "Tán", "Tào", "Tạ", "Tăng", "Thang", "Thái", "Thành", "Thào", "Thạch",
                       "Thân", "Thẩm", "Thập", "Thế", "Thi", "Thiều", "Thịnh", "Thoa", "Thôi", "Thục", "Ty", "Tiêu",
                       "Tiếp", "Tinh", "Tòng", "Tô", "Tôn", "Tông", "Tống", "Trang", "Trác", "Trà", "Tri", "Triệu",
                       "Trình", "Trịnh", "Trưng", "Trương", "Từ", "Uông", "Ung", "Ưng", "Ứng", "Vạn", "Văn", "Vi",
                       "Viêm", "Viên", "Vương", "Vưu", "Xung", "Xa", "Yên", "Chiêu",
                       
